global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: "api"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["app1:80", "app2:80", "app3:80"]

  - job_name: "catalogue-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["catalogue-api-1:80"]

  - job_name: "node-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
