// <auto-generated />
using InventaireMcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventaireMcService.Migrations
{
    [DbContext(typeof(InventaireDbContext))]
    [Migration("20250704134630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventaireMcService.Models.DemandeReapprovisionnement", b =>
                {
                    b.Property<int>("DemandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandeId"));

                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteDemandee")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DemandeId");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("InventaireMcService.Models.StockItem", b =>
                {
                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("MagasinId", "ProduitId");

                    b.ToTable("StockItems");

                    b.HasData(
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 1,
                            Quantite = 400
                        },
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 2,
                            Quantite = 400
                        },
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 3,
                            Quantite = 400
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 1,
                            Quantite = 100
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 2,
                            Quantite = 80
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 1,
                            Quantite = 60
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 3,
                            Quantite = 90
                        },
                        new
                        {
                            MagasinId = 5,
                            ProduitId = 2,
                            Quantite = 100
                        },
                        new
                        {
                            MagasinId = 4,
                            ProduitId = 2,
                            Quantite = 200
                        },
                        new
                        {
                            MagasinId = 5,
                            ProduitId = 1,
                            Quantite = 310
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
