// <auto-generated />
using System;
using AdministrationMcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdministrationMcService.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20250704231640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministrationMcService.Models.Performance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerformanceId"));

                    b.Property<decimal>("ChiffreAffaires")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<int>("NbVentes")
                        .HasColumnType("integer");

                    b.Property<int>("RupturesStock")
                        .HasColumnType("integer");

                    b.Property<int>("Surstock")
                        .HasColumnType("integer");

                    b.HasKey("PerformanceId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            PerformanceId = 1,
                            ChiffreAffaires = 1000m,
                            Date = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            MagasinId = 2,
                            NbVentes = 50,
                            RupturesStock = 2,
                            Surstock = 5
                        },
                        new
                        {
                            PerformanceId = 2,
                            ChiffreAffaires = 1500m,
                            Date = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            MagasinId = 3,
                            NbVentes = 70,
                            RupturesStock = 1,
                            Surstock = 3
                        },
                        new
                        {
                            PerformanceId = 3,
                            ChiffreAffaires = 1100m,
                            Date = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            MagasinId = 2,
                            NbVentes = 55,
                            RupturesStock = 0,
                            Surstock = 4
                        },
                        new
                        {
                            PerformanceId = 4,
                            ChiffreAffaires = 1600m,
                            Date = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            MagasinId = 3,
                            NbVentes = 75,
                            RupturesStock = 2,
                            Surstock = 2
                        },
                        new
                        {
                            PerformanceId = 5,
                            ChiffreAffaires = 1200m,
                            Date = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            MagasinId = 2,
                            NbVentes = 60,
                            RupturesStock = 1,
                            Surstock = 6
                        },
                        new
                        {
                            PerformanceId = 6,
                            ChiffreAffaires = 1700m,
                            Date = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            MagasinId = 3,
                            NbVentes = 80,
                            RupturesStock = 0,
                            Surstock = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
